version: 'v1'
services:
  deployment-production:
    image: batsaikhan84/ims-app:latest
    container_name: ims-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production