export const BOTTOM_TOOLBAR_BUTTONS = {
    DOWNLOAD: 'DOWNLOAD',
    REQUEST_REVIEW: 'REQUEST_REVIEW',
    ADD_ITEM: 'ADD_ITEM'
};

export const STATUS = {
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    PENDING: 'PENDING',
    ORDERED: 'ORDERED',
    BACK_ORDERED: 'BACK_ORDERED',
    PARTIAL_RECEIPT: 'PARTIAL_RECEIPT'
};

export const DEPARTMENT = {
    EXTRACTIONS: 'EXTRACTIONS',
    MASS_SPEC: 'MASS_SPEC',
    RD: 'RD',
    SCREENING: 'SCREENING',
    SHIPPING: 'SHIPPING',
    SPECIMEN_PROCESSING: 'SPECIMEN_PROCESSING',
    QC_INTERNAL_STANDARDS: 'QC_INTERNAL_STANDARDS',
    QUALITY: 'QUALITY',
    STORE_ROOM: 'STORE_ROOM',
    GENERAL: 'GENERAL',
    OFFICE_SUPPLY: 'OFFICE_SUPPLY'
};

export const CONFIRMATION = {
    WAITING: 'WAITING',
    COMPLETE: 'COMPLETE'
};

export const DRAWER_TOGGLE_TYPE = {
    UPDATE_QUANTITY: 'UPDATE_QUANTITY',
    UPDATE_REQUEST_REVIEW: 'UPDATE_REQUEST_REVIEW',
    UPDATE_REQUEST_EDIT: 'UPDATE_REQUEST_EDIT',
    ADD_MASTER_ITEM: 'ADD_MASTER_ITEM',
    UPDATE_MASTER_ITEM: 'UPDATE_MASTER_ITEM',
    ASSIGN_MASTER_ITEM: 'ASSIGN_MASTER_ITE',
    UPDATE_DEPARTMENT_ITEM: 'UPDATE_DEPARTMENT_ITEM'
};

export const CATEGORY = {
    GC: 'GC',
    LC: 'LC',
    COLUMNS: 'COLUMNS',
    GENERAL: 'GENERAL',
    GASES: 'GASES',
    SOLVENTS: 'SOLVENTS',
    LDTD: 'LDTD',
    SCIEX: 'SCIEX'
};

export const ROLE = {
    ADMINISTRATION: 'ADMINISTRATION',
    USER: 'USER'
};

export const PERMISSION = {
    ALLOW: 'ALLOW',
    DENY: 'DENY'
};
