export const departments = {
    'EXTRACTIONS': 'EXTRACTIONS',
    'mass-spec': 'MASS-SPEC',
    'receiving': 'RECEIVING',
    'rd': 'RD',
    'screening': 'SCREENING',
    'shipping': 'SHIPPING',
    'quality': 'QUALITY'
}

export const bottomToolbarButtons = {
    DOWNLOAD: 'DOWNLOAD',
    REQUEST_REVIEW: 'REQUEST_REVIEW',
    ADD_ITEM: 'ADD_ITEM'
}

export const status = {
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    PENDING: 'PENDING',
    ORDERED: 'ORDERED',
    BACK_ORDERED: 'BACK_ORDERED',
    PARTIAL_RECEIPT: 'PARTIAL_RECEIPT'
}

export const department = {
    EXTRACTIONS: 'EXTRACTIONS',
    MASS_SPEC: 'MASS_SPEC',
    RECEIVING: 'RECEIVING',
    RD: 'RD',
    SCREENING: 'SCREENING',
    SHIPPING: 'SHIPPING',
    QUALITY: 'QUALITY',
    ACCOUNTING: 'ACCOUNTING',
    LABORATORY: 'LABORATORY'
}

export const confirmation = {
    WAITING: 'WAITING',
    COMPLETE: 'COMPLETE'
}

export const drawerToggleType = {
    UPDATE_QUANTITY_FORM: 'UPDATE_QUANTITY_FORM',
    UPDATE_REQUEST_REVIEW_FORM: 'UPDATE_REQUEST_REVIEW_FORM',
    UPDATE_REQUEST_EDIT_FORM: 'UPDATE_REQUEST_EDIT_FORM',
    ADD_MASTER_ITEM_FROM: 'ADD_MASTER_ITEM_FROM',
    UPDATE_MASTER_ITEM_FROM: 'UPDATE_MASTER_ITEM_FROM'
}

